import {
  AlertTriangle,
  CheckCircle2,
  ClipboardCopy,
  Download,
  FileText,
  ShieldAlert,
} from "lucide-react";
import React, { useMemo, useState } from "react";
import { fetchReport } from "../lib/api";
import type { AnalysisResult, Signal } from "../lib/types";
import { copyText, downloadText } from "../lib/utils";

type Step = 1 | 2 | 3 | 4;
type Category = "scam" | "predatory" | "suspicious";
type Destination = "platform" | "consumer" | "police";

const APP_URL = "saferent.siddharthsudhir.com";
const DEV_EMAIL = "dev.siddharthsudhir@gmail.com";
const REPORTER_EMAIL_KEY = "saferent:reporterEmail";

function stepLabel(step: Step) {
  if (step === 1) return "Category";
  if (step === 2) return "Evidence";
  if (step === 3) return "Destinations";
  return "Report";
}

function emailOk(v: string) {
  const s = v.trim();
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
}

function signalTitle(s: Signal) {
  const sev = s.severity ? s.severity.toUpperCase() : "";
  const cat = s.category ? s.category.toUpperCase() : "";
  const bits = [cat, sev].filter(Boolean).join(" · ");
  return bits ? `${s.label} (${bits})` : s.label;
}

function formatCheckedAt(d?: string) {
  try {
    if (!d) return new Date().toISOString();
    const dt = new Date(d);
    return isNaN(dt.getTime()) ? new Date().toISOString() : dt.toISOString();
  } catch {
    return new Date().toISOString();
  }
}

export default function Report() {
  const [step, setStep] = useState<Step>(1);
  const [category, setCategory] = useState<Category>("suspicious");
  const [selectedReasons, setSelectedReasons] = useState<string[]>([]);
  const [destinations, setDestinations] = useState<Destination[]>(["platform"]);
  const [note, setNote] = useState<string>("");
  const [reporterEmail, setReporterEmail] = useState<string>(() => {
    return localStorage.getItem(REPORTER_EMAIL_KEY) || "";
  });

  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [md, setMd] = useState<string>("");

  const last = useMemo<AnalysisResult | null>(() => {
    try {
      const raw = localStorage.getItem("saferent:lastAnalysis");
      if (!raw) return null;
      return JSON.parse(raw) as AnalysisResult;
    } catch {
      return null;
    }
  }, []);

  const reasons = useMemo(() => {
    const r = last?.topReasons || [];
    return Array.isArray(r) ? r : [];
  }, [last]);

  const topSignals = useMemo(() => {
    const sigs = Array.isArray(last?.signals) ? [...(last!.signals as Signal[])] : [];
    sigs.sort((a, b) => Math.abs((b.contribution || 0)) - Math.abs((a.contribution || 0)));
    return sigs.slice(0, 8);
  }, [last]);

  const reporterEmailIsOk = emailOk(reporterEmail);

  function toggleReason(r: string) {
    setSelectedReasons((cur) => (cur.includes(r) ? cur.filter((x) => x !== r) : [...cur, r]));
  }

  function toggleDest(d: Destination) {
    setDestinations((cur) => (cur.includes(d) ? cur.filter((x) => x !== d) : [...cur, d]));
  }

  async function onGenerate() {
    if (!last?.analysisId) {
      setErr("No analysis found. Run an analysis first.");
      return;
    }
    if (!reporterEmailIsOk) {
      setErr("Please enter a valid email address (required) before generating the report.");
      setStep(2);
      return;
    }

    setErr(null);
    setBusy(true);
    try {
      // ✅ fetchReport returns a STRING (we fixed the object -> string bug)
      const backendMd = await fetchReport(last.analysisId);

      const checkedAt = formatCheckedAt((last as any).createdAt);
      const listingUrl = last.listing?.source_url || "(manual listing text)";
      const listingTitle = last.listing?.title || "(title not provided)";
      const listingLocation =
        [last.listing?.neighborhood, last.listing?.city, (last.listing as any)?.address_hint]
          .filter(Boolean)
          .join(" · ") || "(location not provided)";
      const listingPrice =
        typeof last.listing?.price === "number" ? `CAD ${last.listing.price}` : "(price not provided)";

      const verdictText =
        last.verdict === "likely_scam"
          ? "likely scam"
          : last.verdict === "likely_predatory"
          ? "predatory / unfair terms"
          : last.verdict === "likely_legit"
          ? "low risk signals"
          : "unclear";

      const destText = destinations
        .map((d) =>
          d === "platform"
            ? "Listing platform"
            : d === "consumer"
            ? "Consumer protection"
            : d === "police"
            ? "Police (non-emergency)"
            : "Other"
        )
        .join(", ");

      const headerLines: string[] = [];
      headerLines.push(`# SAFERENT Report`);
      headerLines.push("");
      headerLines.push(`**Generated by:** SAFERENT (${APP_URL})  `);
      headerLines.push(`**Developer contact:** ${DEV_EMAIL}  `);
      headerLines.push(`**Reporter email:** ${reporterEmail.trim()}  `);
      headerLines.push("");
      headerLines.push(`**Category:** ${category.toUpperCase()}  `);
      headerLines.push(`**Listing URL:** ${listingUrl}  `);
      headerLines.push(`**Listing title:** ${listingTitle}  `);
      headerLines.push(`**Location / hint:** ${listingLocation}  `);
      headerLines.push(`**Advertised price:** ${listingPrice}  `);
      headerLines.push(`**Risk score:** ${last.riskScore}/100 (${verdictText})  `);
      headerLines.push(`**Checked:** ${checkedAt}  `);
      headerLines.push("");

      headerLines.push("## Why this may be an issue");
      if (selectedReasons.length) {
        for (const r of selectedReasons) headerLines.push(`- ${r}`);
      } else if (reasons.length) {
        // fallback: include top reasons if user didn't select any
        for (const r of reasons.slice(0, 6)) headerLines.push(`- ${r}`);
      } else {
        headerLines.push("- No explicit reasons were captured for this analysis.");
      }
      headerLines.push("");

      if (topSignals.length) {
        headerLines.push("## Evidence signals (top)");
        for (const s of topSignals) {
          const contrib = typeof s.contribution === "number" ? ` (impact ${s.contribution.toFixed(2)})` : "";
          headerLines.push(`- ${signalTitle(s)}${contrib}`);
          if (s.why_it_matters) headerLines.push(`  - Why it matters: ${s.why_it_matters}`);
          // Back-end may emit evidence as string OR string[] depending on provider.
          const ev: any = (s as any).evidence;
          if (Array.isArray(ev) && ev.length) headerLines.push(`  - Evidence: ${ev.join("; ")}`);
          else if (typeof ev === "string" && ev.trim()) headerLines.push(`  - Evidence: ${ev.trim()}`);
        }
        headerLines.push("");
      }

      if (note.trim()) {
        headerLines.push("## Reporter note");
        headerLines.push(note.trim());
        headerLines.push("");
      }

      const actions = Array.isArray((last as any).recommendedActions) ? (last as any).recommendedActions : [];
      const redundancy = Array.isArray((last as any).redundancySteps) ? (last as any).redundancySteps : [];
      const dataHints = Array.isArray((last as any).dataQualityHints) ? (last as any).dataQualityHints : [];

      if (actions.length) {
        headerLines.push("## What to do next");
        for (const a of actions) headerLines.push(`- ${a}`);
        headerLines.push("");
      }

      if (redundancy.length) {
        headerLines.push("## If results look off (double-check)");
        for (const r of redundancy) headerLines.push(`- ${r}`);
        headerLines.push("");
      }

      if (dataHints.length) {
        headerLines.push("## Data quality notes");
        for (const h of dataHints) headerLines.push(`- ${h}`);
        headerLines.push("");
      }

      headerLines.push(`**Suggested destinations:** ${destText || "(not selected)"}`);
      headerLines.push("");
      headerLines.push("---");
      headerLines.push("");
      headerLines.push("## Detailed analysis (system)\n");

      const full = headerLines.join("\n") + String(backendMd || "");

      setMd(full);
      setStep(4);
      localStorage.setItem(REPORTER_EMAIL_KEY, reporterEmail.trim());
    } catch (e: any) {
      setErr(e?.message || "Could not generate report.");
    } finally {
      setBusy(false);
    }
  }

  if (!last) {
    return (
      <div className="glass rounded-2xl p-6">
        <div className="text-2xl font-semibold">Report a Listing</div>
        <div className="mt-2 text-sm subtle">
          Run an analysis first, then return here to generate a privacy-safe report.
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="text-center">
        <div
          className="mx-auto grid h-12 w-12 place-items-center rounded-2xl soft-border"
          style={{ background: "rgba(239,68,68,0.10)" }}
        >
          <ShieldAlert />
        </div>
        <div className="mt-4 text-3xl font-semibold">Report a Listing</div>
        <div className="mt-2 text-sm subtle">
          Create a privacy-safe report to submit to platforms or authorities
        </div>
      </div>

      {/* Stepper */}
      <div className="mx-auto flex max-w-3xl items-center justify-center gap-2">
        {[1, 2, 3, 4].map((n) => {
          const s = n as Step;
          const active = step === s;
          const done = step > s;
          return (
            <React.Fragment key={n}>
              <div
                className={
                  "flex items-center gap-2 rounded-2xl px-4 py-2 text-sm transition " +
                  (active ? "chip ring-soft" : done ? "chip" : "soft-border")
                }
                style={!active && !done ? { background: "rgba(255,255,255,0.02)" } : undefined}
              >
                <span
                  className="grid h-6 w-6 place-items-center rounded-full text-xs font-semibold"
                  style={{
                    background: done
                      ? "rgba(34,197,94,0.18)"
                      : active
                      ? "rgba(46,196,255,0.18)"
                      : "rgba(255,255,255,0.06)",
                    border: "1px solid rgba(255,255,255,0.10)",
                  }}
                >
                  {done ? <CheckCircle2 size={14} /> : n}
                </span>
                <span className={active ? "" : "subtle"}>{stepLabel(s)}</span>
              </div>
              {n !== 4 ? (
                <div className="h-px w-6" style={{ background: "rgba(255,255,255,0.10)" }} />
              ) : null}
            </React.Fragment>
          );
        })}
      </div>

      {err ? (
        <div
          className="mx-auto max-w-3xl rounded-2xl p-4"
          style={{
            border: "1px solid rgba(239, 68, 68, 0.25)",
            background: "rgba(239, 68, 68, 0.08)",
          }}
        >
          <div className="text-sm" style={{ color: "rgba(255,255,255,0.92)" }}>
            {err}
          </div>
        </div>
      ) : null}

      {/* Panel */}
      <div className="mx-auto max-w-4xl glass rounded-2xl p-6">
        {step === 1 ? (
          <>
            <div className="text-xl font-semibold">Select Category</div>
            <div className="mt-1 text-sm subtle">What best describes the issue with this listing?</div>

            <div className="mt-5 grid gap-3">
              <button
                type="button"
                onClick={() => setCategory("scam")}
                className={
                  "rounded-2xl p-4 text-left focus-ring transition hover:opacity-95 " +
                  (category === "scam" ? "chip ring-soft" : "chip")
                }
              >
                <div className="flex items-start gap-3">
                  <span
                    className="grid h-9 w-9 place-items-center rounded-2xl"
                    style={{
                      background: "rgba(239,68,68,0.12)",
                      border: "1px solid rgba(239,68,68,0.18)",
                    }}
                  >
                    <AlertTriangle size={18} />
                  </span>
                  <div>
                    <div className="font-semibold">Scam</div>
                    <div className="text-sm subtle">Fake listing, identity theft, advance-fee fraud</div>
                  </div>
                </div>
              </button>

              <button
                type="button"
                onClick={() => setCategory("predatory")}
                className={
                  "rounded-2xl p-4 text-left focus-ring transition hover:opacity-95 " +
                  (category === "predatory" ? "chip ring-soft" : "chip")
                }
              >
                <div className="flex items-start gap-3">
                  <span
                    className="grid h-9 w-9 place-items-center rounded-2xl"
                    style={{
                      background: "rgba(245,158,11,0.12)",
                      border: "1px solid rgba(245,158,11,0.18)",
                    }}
                  >
                    <FileText size={18} />
                  </span>
                  <div>
                    <div className="font-semibold">Predatory</div>
                    <div className="text-sm subtle">Hidden fees, bait-and-switch, discrimination</div>
                  </div>
                </div>
              </button>

              <button
                type="button"
                onClick={() => setCategory("suspicious")}
                className={
                  "rounded-2xl p-4 text-left focus-ring transition hover:opacity-95 " +
                  (category === "suspicious" ? "chip ring-soft" : "chip")
                }
              >
                <div className="flex items-start gap-3">
                  <span
                    className="grid h-9 w-9 place-items-center rounded-2xl"
                    style={{
                      background: "rgba(46,196,255,0.12)",
                      border: "1px solid rgba(46,196,255,0.18)",
                    }}
                  >
                    <ShieldAlert size={18} />
                  </span>
                  <div>
                    <div className="font-semibold">Suspicious</div>
                    <div className="text-sm subtle">Unusual patterns, needs investigation</div>
                  </div>
                </div>
              </button>
            </div>

            <div className="mt-6 flex items-center justify-between">
              <div className="text-xs subtle">This does not submit anything automatically.</div>
              <button type="button" className="btn" onClick={() => setStep(2)}>
                Continue
              </button>
            </div>
          </>
        ) : null}

        {step === 2 ? (
          <>
            <div className="text-xl font-semibold">Evidence</div>
            <div className="mt-1 text-sm subtle">Choose the evidence you want to include in the report.</div>

            <div className="mt-4">
              <div className="text-sm font-semibold">Your email (required)</div>
              <div className="mt-1 text-sm subtle">Platforms or authorities can reply to this email.</div>
              <input
                className="input mt-2"
                placeholder="you@example.com"
                value={reporterEmail}
                onChange={(e) => setReporterEmail(e.target.value)}
              />
              {reporterEmail && !reporterEmailIsOk ? (
                <div className="mt-2 text-xs" style={{ color: "rgba(239, 68, 68, 0.92)" }}>
                  Please enter a valid email address.
                </div>
              ) : null}
            </div>

            <div className="mt-5 grid gap-2">
              {reasons.length ? (
                reasons.map((r) => {
                  const on = selectedReasons.includes(r);
                  return (
                    <button
                      key={r}
                      type="button"
                      onClick={() => toggleReason(r)}
                      className={
                        "rounded-2xl p-3 text-left focus-ring transition hover:opacity-95 " +
                        (on ? "chip ring-soft" : "chip")
                      }
                    >
                      <div className="flex items-center justify-between gap-3">
                        <div className="text-sm" style={{ color: "rgba(255,255,255,0.92)" }}>
                          {r}
                        </div>
                        <div
                          className="grid h-6 w-6 place-items-center rounded-full"
                          style={{
                            background: on ? "rgba(34,197,94,0.18)" : "rgba(255,255,255,0.06)",
                            border: "1px solid rgba(255,255,255,0.10)",
                          }}
                        >
                          {on ? <CheckCircle2 size={14} /> : null}
                        </div>
                      </div>
                    </button>
                  );
                })
              ) : (
                <div className="rounded-2xl chip p-4 text-sm subtle">No top reasons available for this analysis.</div>
              )}
            </div>

            <div className="mt-4">
              <div className="text-sm font-semibold">Add a short note (optional)</div>
              <textarea
                className="textarea mt-2"
                placeholder="Example: The lister asked for e-transfer deposit before viewing."
                value={note}
                onChange={(e) => setNote(e.target.value)}
              />
            </div>

            <div className="mt-6 flex items-center justify-between">
              <button
                type="button"
                className="px-4 py-2 rounded-xl focus-ring"
                onClick={() => setStep(1)}
                style={{
                  border: "1px solid rgba(255,255,255,0.12)",
                  background: "rgba(255,255,255,0.04)",
                  color: "rgba(255,255,255,0.92)",
                }}
              >
                Back
              </button>
              <button type="button" className="btn" onClick={() => setStep(3)} disabled={!reporterEmailIsOk}>
                Continue
              </button>
            </div>
          </>
        ) : null}

        {step === 3 ? (
          <>
            <div className="text-xl font-semibold">Destinations</div>
            <div className="mt-1 text-sm subtle">Select where you plan to submit this report.</div>

            <div className="mt-5 grid gap-3">
              <button
                type="button"
                onClick={() => toggleDest("platform")}
                className={
                  "rounded-2xl p-4 text-left focus-ring transition hover:opacity-95 " +
                  (destinations.includes("platform") ? "chip ring-soft" : "chip")
                }
              >
                <div className="font-semibold">Listing platform</div>
                <div className="text-sm subtle">Report the listing and attach your evidence.</div>
              </button>

              <button
                type="button"
                onClick={() => toggleDest("consumer")}
                className={
                  "rounded-2xl p-4 text-left focus-ring transition hover:opacity-95 " +
                  (destinations.includes("consumer") ? "chip ring-soft" : "chip")
                }
              >
                <div className="font-semibold">Consumer protection</div>
                <div className="text-sm subtle">Useful for patterns of fraud or unfair terms.</div>
              </button>

              <button
                type="button"
                onClick={() => toggleDest("police")}
                className={
                  "rounded-2xl p-4 text-left focus-ring transition hover:opacity-95 " +
                  (destinations.includes("police") ? "chip ring-soft" : "chip")
                }
              >
                <div className="font-semibold">Police (non-emergency)</div>
                <div className="text-sm subtle">For clear fraud attempts, threats, or repeated scams.</div>
              </button>
            </div>

            <div className="mt-6 flex items-center justify-between">
              <button
                type="button"
                className="px-4 py-2 rounded-xl focus-ring"
                onClick={() => setStep(2)}
                style={{
                  border: "1px solid rgba(255,255,255,0.12)",
                  background: "rgba(255,255,255,0.04)",
                  color: "rgba(255,255,255,0.92)",
                }}
              >
                Back
              </button>
              <button type="button" className="btn" onClick={onGenerate} disabled={busy}>
                {busy ? "Generating…" : "Generate"}
              </button>
            </div>
          </>
        ) : null}

        {step === 4 ? (
          <>
            <div className="text-xl font-semibold">Generated Report</div>
            <div className="mt-1 text-sm subtle">Copy or download. Remove personal info before sharing.</div>

            <div className="mt-4 flex flex-wrap gap-2">
              <button
                type="button"
                onClick={() => copyText(md)}
                className="chip rounded-xl px-3 py-2 text-sm focus-ring transition hover:opacity-95"
              >
                <span className="inline-flex items-center gap-2">
                  <ClipboardCopy size={16} /> Copy
                </span>
              </button>
              <button
                type="button"
                onClick={() => downloadText("SAFERENT-Report.md", md)}
                className="chip rounded-xl px-3 py-2 text-sm focus-ring transition hover:opacity-95"
              >
                <span className="inline-flex items-center gap-2">
                  <Download size={16} /> Download
                </span>
              </button>
            </div>

            <pre
              className="mt-4 whitespace-pre-wrap break-words rounded-2xl p-4 soft-border"
              style={{ background: "rgba(0,0,0,0.20)" }}
            >
              {md || "(No report generated yet.)"}
            </pre>

            <div className="mt-6 flex items-center justify-between">
              <button
                type="button"
                className="px-4 py-2 rounded-xl focus-ring"
                onClick={() => setStep(3)}
                style={{
                  border: "1px solid rgba(255,255,255,0.12)",
                  background: "rgba(255,255,255,0.04)",
                  color: "rgba(255,255,255,0.92)",
                }}
              >
                Back
              </button>
              <button type="button" className="btn" onClick={() => setStep(1)}>
                Start Over
              </button>
            </div>
          </>
        ) : null}
      </div>

      {/* Small footer note */}
      <div className="mx-auto max-w-4xl text-center text-xs subtle">
        Generated by SAFERENT ({APP_URL}). For support or feedback: {DEV_EMAIL}.
      </div>
    </div>
  );
}
